apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: test-cd
spec:
  gitImplementation: libgit2
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
# apiVersion: source.toolkit.fluxcd.io/v1beta1
# kind: GitRepository
# metadata:
#   name: flux2-kustomize-helm-example
#   namespace: test-cd
# spec:
#   gitImplementation: libgit2
#   interval: 1m
#   url: https://github.com/fluxcd/flux2-kustomize-helm-example
#   ref:
#     branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
  namespace: test-cd
spec:
  interval: 10m
  targetNamespace: test-cd
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: "./kustomize"
  prune: true
  timeout: 1m
  patchesJson6902:
  - patch:
    - op: add
      path: /metadata/labels
      value:
        test: patchesJson6902
        bar: test
    target:
      kind: Deployment
      name: podinfo
